name: Despliegue de Producción
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./pronalfut_website-main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4

      # --- ESTE ES EL PASO NUEVO PARA CORREGIR EL ERROR ---
      - name: Configurar Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./pronalfut_website-main/package-lock.json
      # ----------------------------------------------------

      - name: Instalación de dependencias
        run: npm install

      - name: Construcción del proyecto
        run: npm run build

      - name: Despliegue a Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './pronalfut_website-main/dist'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./pronalfut_website-main/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
